name: ChestLocker
main: ChestLocker\Main
version: "1.0.0"
api: [1.2.0]
load: STARTUP
author: XuxuGzs
description: Lock/Unlock The Chests.
website: http://www.xubw.cn

commands:
 chestlocker:
   aliases: [chlock, chl, chestlock, cl]
   description: ChestLocker Commands.
 lock:
   description: Lock Chest.
 unlock:
   description: Unlock Chest.
 pwdlock:
   description: Password Lock Chest.
 pwdunlock:
   description: Password Unlock Chest.
permissions:
 chestlocker:
  default: true
  description: ChestLocker permissions.
  children:
   chestlocker.bypass:
    default: op
    description: Bypass Chest lock.
   chestlocker.commands:
    default: true
    description: ChestLocker commands permissions.
    children:
      chestlocker.commands.help:
       default: true
       description: ChestLocker command Help permission.
      chestlocker.commands.info:
       default: op
       description: ChestLocker command Info permission.
      chestlocker.commands.reload:
       default: op
       description: ChestLocker command Reload permission.
      chestlocker.commands.lockchest:
       default: true
       description: ChestLocker command LockChest permission.
      chestlocker.commands.unlockchest:
       default: true
       description: ChestLocker command UnlockChest permission.
      chestlocker.commands.pwdlockchest:
       default: true
       description: ChestLocker command Password LockChest permission.
      chestlocker.commands.pwdunlockchest:
       default: true
       description: ChestLocker command Password UnlockChest permission.